### ISSUE TITLE
Link in about box is dead

### ISSUE THREAD

**Issue by diesl** [heartcombo/simple_form-bootstrap#319]
Hello,

the link in the **About** section of the Index page is dead. 

Maybe you want to update it like you did here: https://github.com/rafaelfranca/simple_form-bootstrap/commit/e94574d6ad5ec317a43a2ea3064a769a4de27fcb

**Comment by m5o** [comment]
@rafaelfranca Can you help here? I don’t have the permission to change that.

**Comment by carlosantoniodasilva** [comment]
Fixed now, thanks!
