### ISSUE TITLE
bootstrap 5 dropped .form-group

### ISSUE THREAD

**Issue by namiwang** [heartcombo/simple_form-bootstrap#323]
https://getbootstrap.com/docs/5.0/migration/#forms-2

**Comment by m5o** [comment]
hi @namiwang 

At the moment the demo and generator isn’t updated for the `v5.0.0-beta1` of bootstrap. There is also no specific date when the transition is finally done. As written in the migration guide you posted, `.form-group` was removed from the margin utils. 

> Dropped `.form-group` for margin utilities (we’ve replaced our docs examples with `.mb-3`).

For now use a workaround, append the `.mb-3` CSS class were `.form-group` is exposed.

**Comment by yshmarov** [comment]
In bootstrap 5 the following form:
```
<%= simple_form_for(@plan) do |f| %>
  <%= f.input :currency, collection: [ "usd", "eur", "pln", "uah", "rub"], include_blank: false %>
  <%= f.input :interval, collection: ["month", "year", "forever"], as: :radio_buttons %>
  <%= f.input :max_members %>
  <%= f.button :submit %>
<% end %>
```
provides this view:
![image](https://user-images.githubusercontent.com/13472945/112235229-81e40f00-8c3e-11eb-98de-3af4442869df.png)

Below is the same code with bootstrap 4. As you see in the image **above** the collection dropdown does not work + radio buttons are floating around
![image](https://user-images.githubusercontent.com/13472945/112235146-56612480-8c3e-11eb-822f-8b038074ad90.png)
